id: P14EDB778
initial_creation_type: input
source_metadata:
  title: Auspiciousness Series
  language: es
  description: 'A selection of texts on the theme of auspiciousness (maṅgalam; bkra
    shis) including verses of auspiciousness (maṅgalagāthā) and prayers:'
  volume:
    8c7a1f18e6714f9cad21fa42866a9dec:
      title: A Prayer for Auspiciousness
      parent: Verses of Auspiciousness
    d18934771f47424c8eadd48e87858ba0:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Verses of Auspiciousness
    2a93f26e1eeb4cda9448286c371b5d00:
      title: Verses of Auspiciousness
      parent: Verses of Auspiciousness
    10ea5bc8cdac4980a554555e6e4bc97d:
      title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness
        and Wellbeing'
      parent: Verses of Auspiciousness
    ab96250e71c74b32bbf128624b5741fa:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Verses of Auspiciousness
created_at: '2022-03-01T02:52:02.800119'
last_modified_at: '2022-03-01T02:52:02.800121'
